name: ServerPatcher
version: '1.0.5'
main: dev.hyperskys.serverpatcher.ServerPatcher
api-version: 1.17
authors: [ HyperSkys ]
depend:
  - ProtocolLib
description: Patches exploits before Mojang does so you don't have to worry about it.
website: www.hyperskys.dev
commands:
  serverpatcher:
    description: Main command for the plugin
    aliases: [spatcher]